# 服务器配置
server:
  port: 8080
  mode: debug # debug, release, test

# 数据库配置
database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: chitchat
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

# JWT配置
jwt:
  secret: your_jwt_secret_key
  expire: 24h # 过期时间

# 文件上传配置
upload:
  max_size: 5 # MB
  allowed_types: [image/jpeg, image/png, image/gif]
  storage_path: ./uploads

# Redis配置（可选）
redis:
  enabled: false
  host: localhost
  port: 6379
  password: ""
  db: 0
